development:
  adapter: postgresql
  encoding: unicode
  database: tweet_dev
  pool: 5
  username: oleg
  password: 664578
test:
  adapter: postgresql
  encoding: unicode
  database: tweet_test
  pool: 5
  username: oleg
  password: 664578
production:
  adapter: postgresql
  encoding: unicode
  database: tweet_production
  pool: 5
  username: deployer
  password: 66457866
